### ISSUE TITLE
PRAISE - possibility of rounding errors in balanceUnderlying() found in CompoundProvider.sol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#112]
PRAISE

medium

# possibility of rounding errors in balanceUnderlying() found in CompoundProvider.sol

## Summary
rounding error
## Vulnerability Detail
There is a possibility of rounding errors in the calculation: (balanceShares * price) / 10 ** (10 + decimals).

## Impact
The division operation:  '(balanceShares * price) / 10 ** (10 + decimals)' may result in a fractional value that cannot be represented exactly in the given number of decimal places. This can cause a loss of precision in the calculation, leading to rounding errors.

For example, if balanceShares is 100 and price is 1.23, and decimals is 18 (the standard for Ethereum tokens), then the result of (balanceShares * price) would be 123. However, when this value is divided by 10 ** (10 + decimals), the result would be 0.000000000000123, which cannot be represented exactly in 18 decimal places.

## Code Snippet
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Providers/CompoundProvider.sol#L99

## Tool used

Manual Review

## Recommendation
...maybe don't divide by 10 ** (10 + decimals).

**Comment by dmitriia** [comment]
Escalate for 10 USDC
I'm sorry, but as it is this looks invalid, as no vulnerability was demonstrated.

The only explanation incorrectly ignores decimals of the numbers involved:

> For example, if balanceShares is 100 and price is 1.23, and decimals is 18 (the standard for Ethereum tokens), then the
> result of (balanceShares * price) would be 123. However, when this value is divided by 10 ** (10 + decimals), the result
> would be 0.000000000000123, which cannot be represented exactly in 18 decimal places.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> I'm sorry, but as it is this looks invalid, as no vulnerability was demonstrated.
> 
> The only explanation incorrectly ignores decimals of the numbers involved:
> 
> > For example, if balanceShares is 100 and price is 1.23, and decimals is 18 (the standard for Ethereum tokens), then the
> > result of (balanceShares * price) would be 123. However, when this value is divided by 10 ** (10 + decimals), the result
> > would be 0.000000000000123, which cannot be represented exactly in 18 decimal places.
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Love4codes** [comment]
> Escalate for 10 USDC I'm sorry, but as it is this looks invalid, as no vulnerability was demonstrated.
> 
> The only explanation incorrectly ignores decimals of the numbers involved:
> 
> > For example, if balanceShares is 100 and price is 1.23, and decimals is 18 (the standard for Ethereum tokens), then the
> > result of (balanceShares * price) would be 123. However, when this value is divided by 10 ** (10 + decimals), the result
> > would be 0.000000000000123, which cannot be represented exactly in 18 decimal places.

Please note that i have clearly shown here how The division operation: '(balanceShares * price) / 10 ** (10 + decimals)' may  cause a **loss of precision** in the calculation, leading to **rounding errors**.

**Comment by dmitriia** [comment]
Rounding per se is a normal behavior of integer arithmetic.

Any issue should clearly demonstrate the impact, i.e. the burden of proof is on reporter.

**Comment by Love4codes** [comment]
> Rounding per se is a normal behavior of integer arithmetic.
> 
> Any issue should clearly demonstrate the impact, i.e. the burden of proof is on reporter.

Hey! the impact was clearly shown by the watson or maybe you choose not to see. 

The watson has shown how in some situations the division operation: '(balanceShares * price) / 10 ** (10 + decimals)' may result in a fractional value that cannot be represented exactly in `18 decimal places` due to loss of precision which should be a valid vulnerability when dealing with tokens.

**Comment by hrishibhat** [comment]
Escalation accepted

Not a valid duplicate of #202 
Not valid a valid high/medium
It is clear that the above issue does not identify & explain the vulnerability as shown in #202 or #329

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Not a valid duplicate of #202 
> Not valid a valid high/medium
> It is clear that the above issue does not identify & explain the vulnerability as shown in #202 or #329 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
