### ISSUE TITLE
rvierdiiev - XProvider.xTransfer can send not enough amount as relayer fee, as result tx will be waiting for execution for a long time

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#133]
rvierdiiev

medium

# XProvider.xTransfer can send not enough amount as relayer fee, as result tx will be waiting for execution for a long time

## Summary
XProvider.xTransfer can send not enough amount as relayer fee, as result tx will be waiting for execution for a long time.
## Vulnerability Detail
XProvider.xTransfer is created for sending funds using `connext`. Each connext `xCall` should pay fee for relayers.
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L133-L161
```solidity
  function xTransfer(
    address _token,
    uint256 _amount,
    address _recipient,
    uint32 _destinationDomain,
    uint256 _slippage,
    uint256 _relayerFee
  ) internal {
    require(
      IERC20(_token).allowance(msg.sender, address(this)) >= _amount,
      "User must approve amount"
    );


    // User sends funds to this contract
    IERC20(_token).transferFrom(msg.sender, address(this), _amount);


    // This contract approves transfer to Connext
    IERC20(_token).approve(address(connext), _amount);


    IConnext(connext).xcall{value: (msg.value - _relayerFee)}(
      _destinationDomain, // _destination: Domain ID of the destination chain
      _recipient, // _to: address receiving the funds on the destination
      _token, // _asset: address of the token contract
      msg.sender, // _delegate: address that can revert or forceLocal on destination
      _amount, // _amount: amount of tokens to transfer
      _slippage, // _slippage: the maximum amount of slippage the user will accept in BPS (e.g. 30 = 0.3%)
      bytes("") // _callData: empty bytes because we're only sending funds
    );
  }
```

As you can see, this function is setting `msg.value - _relayerFee` as payment for relayers. And `XProvider.xSend` sets [msg.value or relayerFee](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L113). 
Why it's done in such way? Because some function of  `XProvider` should send 2 connext txs in same time, so they should pay relayerFee 2 times.

For example [`xTransferToController` function](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L332-L333) and [`xTransferToVaults` function](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L374-L375).

So the idea is next, both that function are called with msg.value == relayerFee*2. So 1 part(one relayerFee) is paid for 1 tx, and another is paid for another tx.

But the problem is that there is no check, that `msg.value==relayerFee*2`. Because of that function `xTransferToVaults` can pass in order if `msg.value >= relayerFee && msg.value < relayerFee`. As for first tx relayerFee will be passed(which is ok), but for second(xTransfer) `msg.value - relayerFee` will be passed, which can be small value.
As result seconds tx can be waiting for along time, once any relayer will execute it. And protocol will need to bump it and increase fee.

Example.
1.Current relayer fee is 0.01 eth.
2.Someone calls `XChainController.sendFundsToVault` which triggers `XProvider.xTransferToVaults` and provides 0.011 eth(by mistake) as msg.value and 0.01 as `_relayerFee`.
3.`pushFeedbackToVault` [paid](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L374) `_relayerFee` as fee, so it's 0.001 eth left
4.`xTransfer` [paid](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L375) 0.001 eth as fee.
5.As result `xTransfer` tx was sent with small fee, so it can be stucked for a long time, when any relayer will execute it
## Impact
Tx can be stuck as small relayer fee is provided.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Check that `msg.value==relayerFee*2`

**Comment by rvierdiiev** [comment]
Escalate for 10 usdc.
This is not duplicate of #390.
#390 talks about lack of access control, while this issue is talking about incorrect calculation of provided payment inside `XProvider`.
So even when #390 is fixed, so only team members can trigger bridge function, it's still possible for them to get into troubles when sending wrong fee amount. When #390 is fixed, this bug still occurs.
I believe it's valid medium.

**Comment by sherlock-admin** [comment]
> Escalate for 10 usdc.
> This is not duplicate of #390.
> #390 talks about lack of access control, while this issue is talking about incorrect calculation of provided payment inside `XProvider`.
> So even when #390 is fixed, so only team members can trigger bridge function, it's still possible for them to get into troubles when sending wrong fee amount. When #390 is fixed, this bug still occurs.
> I believe it's valid medium.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Not a valid duplicate of #390 
However, sending an incorrect relayer fee resulting in an unsuccessful transaction is not a valid high/medium.

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Not a valid duplicate of #390 
> However, sending an incorrect relayer fee resulting in an unsuccessful transaction is not a valid high/medium. 
> 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
