### ISSUE TITLE
Ch_301 - Rebalancing with wrong values

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#144]
Ch_301

medium

# Rebalancing with wrong values

## Summary
From the **README** 
**Guardian**: the guardian is there to manually restart the protocol when it's stuck during rebalancing or cross-chain rebalancing. The guardian is controlled by a single entity because it needs to be able to act quickly.

So we know that the **Guardian** should be able to restart the protocol manually when it's stuck during cross-chain rebalancing.

## Vulnerability Detail
When you invoke the function [pushAllocationsToController()](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Game.sol#L424-L445) is to pushes the  `totalDeltaAllocations` from **Game** to **xChainController**
Also, it calls `allocationsToArray()` internally and in turn it set all the **deltaAllocationChain** to zero

```solidity
  function allocationsToArray(uint256 _vaultNumber) internal returns (int256[] memory deltas) {
    deltas = new int[](chainIds.length);

    for (uint256 i = 0; i < chainIds.length; i++) {
      uint32 chain = chainIds[i];
      deltas[i] = getDeltaAllocationChain(_vaultNumber, chain);
      vaults[_vaultNumber].deltaAllocationChain[chain] = 0;
    }
  }
```
The  `pushAllocations()` uses `xcall()` to do the cross-chain message. If the call on the receiver contract reverts because of the `onlyWhenReady()` modifier on **xChainController** or a stuck during cross-chain message

The **Guardian** should be able to restart the protocol manually
He has the ability to invoke `pushAllocationsToController()` at anytime because this `rebalanceNeeded()`
Also, he can call `setRebalancingPeriod()` to set the rebalancing period for vaultNumber to the right number

But the `allocationsToArray()` will return an empty array. Because all the deltas are deleted on the first try   

**NOTE**
The same thing could happen with `pushAllocationsToVaults()`
because `protocolAllocationsToArray()` delete the values of the `deltaAllocationProtocol`
## Impact
**xChainController** will receive an  empty array (deltas) and that will lead the protocol to not working properly (rebalancing with wrong values)

## Code Snippet
```solidity
  function pushAllocationsToController(uint256 _vaultNumber) external payable {
    require(rebalanceNeeded(), "No rebalance needed");
    for (uint k = 0; k < chainIds.length; k++) {
      require(
        getVaultAddress(_vaultNumber, chainIds[k]) != address(0),
        "Game: not a valid vaultnumber"
      );
      require(
        !isXChainRebalancing[_vaultNumber][chainIds[k]],
        "Game: vault is already rebalancing"
      );
      isXChainRebalancing[_vaultNumber][chainIds[k]] = true;
    }

    int256[] memory deltas = allocationsToArray(_vaultNumber);
    IXProvider(xProvider).pushAllocations{value: msg.value}(_vaultNumber, deltas);

    lastTimeStamp = block.timestamp;
    vaults[_vaultNumber].rebalancingPeriod++;

    emit PushedAllocationsToController(_vaultNumber, deltas);
  }
```
## Tool used

Manual Review

## Recommendation
`allocationsToArray()` should not set `deltaAllocationChain` to zeros in this step

**Comment by Ch-301** [comment]
Escalate for 10 USDC

The scenario is possible and this is why the Guardian role exists (to manually restart the protocol when it's stuck during rebalancing or cross chain rebalancing) 
and I describe how `allocationsToArray()` will return zero `deltaAllocationChain` values and this will lead to a defect in the rebalancing process.  

This should be valid

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> The scenario is possible and this is why the Guardian role exists (to manually restart the protocol when it's stuck during rebalancing or cross chain rebalancing) 
> and I describe how `allocationsToArray()` will return zero `deltaAllocationChain` values and this will lead to a defect in the rebalancing process.  
> 
> This should be valid 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Theezr** [comment]
@Ch-301 
This true. But it is not intended to revert the call on the sending contract, because the state already changed like you mentioned. The Guardian is suppose to call the guardian function on the receiving contract, the xChainController (receiveAllocationsFromGameGuard) in this case.

**Comment by hrishibhat** [comment]
Escalation rejected

There is no issue and the code works as intended as pointed by the Sponsor.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> There is no issue and the code works as intended as pointed by the Sponsor. 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
