### ISSUE TITLE
Ch_301 - The vault will send lower values, even if it can provide the required amount from `xChainController`.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#197]
Ch_301

high

# The vault will send lower values, even if it can provide the required amount from `xChainController`.

## Vulnerability Detail
On [pullFunds()](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L111-L127) If the this condition is `true`
```solidity
uint256 amountToWithdraw = shortage > balanceProtocol ? balanceProtocol : shortage;
```
That's means the `amountToWithdraw` value is less than `shortage`
So the vault should keep withdrawing From Protocols

But if this condition is `true`
```solidity
if (amountToWithdraw < minimumPull) break;
```
only means the value of the `vault` on the `i` Protocol is `< minimumPull`
```solidity
uint256 balanceProtocol = balanceUnderlying(I);
```
This will just `break` even if the vault can provide the required amount from `xChainController`.
 and the `rebalanceXChain()` will only send the available balance on this vault to `xChainController`

## Impact
The vault will send lower values, even if it can provide the required amount from `xChainController`.

## Tool used

Manual Review

## Recommendation
You need to make sure there are no funds in the rest protocols to `if (amountToWithdraw < minimumPull) break; `

Duplicate of #273

**Comment by Ch-301** [comment]
Escalate for 10 USDC

This should be a duplicate of #273

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This should be a duplicate of #273 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #273

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #273 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
