### ISSUE TITLE
SunSec - Gas griefing/theft is possible on unsafe external call

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#21]
SunSec

medium

# Gas griefing/theft is possible on unsafe external call

## Vulnerability Detail
This opens up a new attack-vector in the contract and it is gas griefing. Now (bool success, ) is actually the same as writing (bool success, bytes memory data) which basically means that even though the data is omitted it doesn’t mean that the contract does not handle it. Actually, the way it works is the bytes data that was returned from the receiver will be copied to memory. Memory allocation becomes very costly if the payload is big, so this means that if a receiver implements a fallback function that returns a huge payload, then the msg.sender of the transaction, in our case the relayer, will have to pay a huge amount of gas for copying this payload to memory. [REF](https://github.com/pashov/audits/blob/master/solo/Zerem-security-review.md#m-03-gas-griefingtheft-is-possible-on-unsafe-external-call)

`    (bool success, ) = address(this).call(_callData);  //@audit Gas griefing`
## Impact
Malicious actor can launch a gas griefing attack on a relayer. Since griefing attacks have no economic incentive for the attacker and it also requires relayers it should be Medium severity.

funcation call flow: xSend -> xcall -> xReceive -> address(this).call(_callData);
Impacted funcations that use xSend():
pushAllocations
pushTotalUnderlying
pushSetXChainAllocation
pushFeedbackToXController
pushFeedbackToVault
pushProtocolAllocationsToVault
pushRewardsToGame
pushStateFeedbackToVault

## Code Snippet
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L178

```solidity
  function xReceive(
    bytes32 _transferId,
    uint256 _amount,
    address _asset,
    address _originSender,
    uint32 _origin,
    bytes memory _callData
  ) external onlySource(_originSender, _origin) returns (bytes memory) {
    (bool success, ) = address(this).call(_callData);  //@audit Gas griefing
    require(success, "xReceive: No success");
  }
```

## Tool used
Manual Review

## Recommendation
Use a low-level assembly call since it does not automatically copy return data to memory

```solidity
bool success;
assembly {
    success := call(3000, receiver, amount, 0, 0, 0)
}
```

**Comment by hrishibhat** [comment]
Not a valid high/medium
