### ISSUE TITLE
Ch_301 - The protocol will set wrong allocations to a chain without a protocol (blacklisted)

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#215]
Ch_301

medium

# The protocol will set wrong allocations to a chain without a protocol (blacklisted)

## Vulnerability Detail
In case the vault has only one protocol on it, which gets blacklisted over time by [blacklistProtocol()](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L477-L483).
The **Guardian** should be able to set the value of `vaults[_vaultNumber].currentAllocationPerChain[_chainId]` of this chain to `zero` on `xChainController`.
In order to keep the protocol working properly

During the rebalancing, `xChainController` will `settleCurrentAllocation()` with wrong allocations, because allocations on the vault are `zero` but in `xChainController` are `> 0`
 This will lead to locking some funds in the vault every period 

## Impact
The funds are locked in the vault every period without generating any reward 

## Tool used

Manual Review

## Recommendation
The **Guardian** should be able to set the value of `vaults[_vaultNumber].currentAllocationPerChain[_chainId]` 

Duplicate of #94

**Comment by Ch-301** [comment]
Escalate for 10 USDC

This scenario was confirmed by the Sponsor
![image](https://user-images.githubusercontent.com/20110644/231133208-72db58bc-3390-48c9-9e66-4be0978c0ec7.png)

so the Guardian should be able to handle it by updating this value `vaults[_vaultNumber].currentAllocationPerChain[_chainId]` on `xChainController.sol` with some updating on `game.sol` to make sure everything is okay

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This scenario was confirmed by the Sponsor
> ![image](https://user-images.githubusercontent.com/20110644/231133208-72db58bc-3390-48c9-9e66-4be0978c0ec7.png)
> 
> so the Guardian should be able to handle it by updating this value `vaults[_vaultNumber].currentAllocationPerChain[_chainId]` on `xChainController.sol` with some updating on `game.sol` to make sure everything is okay

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Considering this issue as a duplicate of #94/#95

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Considering this issue as a duplicate of #94/#95

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
