### ISSUE TITLE
Ch_301 - The `Guardian` won't be able to set the `Yearn` protocol to the blacklist

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#217]
Ch_301

high

# The `Guardian` won't be able to set the `Yearn` protocol to the blacklist

## Summary
From [Yearn Docs](https://docs.yearn.finance/getting-started/products/yvaults/vault-tokens)
```diff
For example, if you deposit YFI in a yVault you will receive yvYFI in return. yvYFI would be the yVault Token.

If your yVault generates profit, the share price of your yVault tokens will increase. 
This happens because there are more underlying tokens in the yVault to redeem upon withdrawal.
```

So the `balanceUnderlying()` with **Yearn** protocol could keep returning increased amounts over time

## Vulnerability Detail
in case you have only one protocol **Yearn** on this vault. which will need to be blacklisted over time 
[blacklistProtocol()](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L477-L483) will revert because  `balanceProtocol > savedTotalUnderlying`

## Impact
The **Guardian** won't be able to set the **Yearn** protocol (or any other with the same idea) to the blacklist

## Code Snippet
```solidity
  function blacklistProtocol(uint256 _protocolNum) external onlyGuardian {
    uint256 balanceProtocol = balanceUnderlying(_protocolNum);
    currentAllocations[_protocolNum] = 0;
    controller.setProtocolBlacklist(vaultNumber, _protocolNum);
    savedTotalUnderlying -= balanceProtocol;
    withdrawFromProtocol(_protocolNum, balanceProtocol);
  }
```
## Tool used

Manual Review

## Recommendation
You should just set `savedTotalUnderlying` to zero

Duplicate of #280

**Comment by spyrosonic10** [comment]
Escalate for 10 USDC

This is not a duplicate of 280 as both differ in root cause, scenario and fixes and not even medium.
Also there are lot's of edge cases here which is not the case with 280. You can read more [here](https://github.com/sherlock-audit/2023-01-derby-judging/issues/280#issuecomment-1503307959)
- System have to have only 1 provider
- It has to Yearn or yearn like
- When an ecosystem has 1 provider, why would it blacklist it? Set weight zero, rebalance and move on.

So based on the above points, this issue does not even sound “medium” when comparing it to 280.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This is not a duplicate of 280 as both differ in root cause, scenario and fixes and not even medium.
> Also there are lot's of edge cases here which is not the case with 280. You can read more [here](https://github.com/sherlock-audit/2023-01-derby-judging/issues/280#issuecomment-1503307959)
> - System have to have only 1 provider
> - It has to Yearn or yearn like
> - When an ecosystem has 1 provider, why would it blacklist it? Set weight zero, rebalance and move on.
> 
> So based on the above points, this issue does not even sound “medium” when comparing it to 280.
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Not a duplicate of #280 
As they mention different scenario's. Impact of this issue and given the workaround for this, considering this issue a low/Informational

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Not a duplicate of #280 
> As they mention different scenario's. Impact of this issue and given the workaround for this, considering this issue a low/Informational

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
