### ISSUE TITLE
R-Nemes - Unsafe use of ERC20 approve

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#224]
R-Nemes

medium

# Unsafe use of ERC20 approve

---
name: 'unsafe ERC20 approve'
about: 'Reset approval before setting approval'
title: 'Use of unsafe ERC20 approve without reset to zero'
labels: 'Medium'
assignees: ''
---

## Summary
It is recommended to reduce the spender allowance to zero before each approve(<SPENDER>, <AMOUNT>) call.

## Vulnerability Detail
IERC20.approve() function is called without setting the allowance to zero. Some tokens, like USDT, require first reducing the address' allowance to zero by calling approve(_spender, 0).

## Impact
Some tokens, like USDT, require first reducing the address' allowance to zero by calling approve(_spender, 0). Transactions will revert when using an unsupported token like USDT

## Code Snippet
[contracts/XProvider.sol#L150](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L150)

## Tool used

Manual review

## Recommendation
```diff
--- a/derby-yield-optimiser/contracts/XProvider.sol
+++ b/derby-yield-optimiser/contracts/XProvider.sol
@@ -147,7 +147,8 @@ contract XProvider is IXReceiver {
     IERC20(_token).transferFrom(msg.sender, address(this), _amount);
 
     // This contract approves transfer to Connext
-    IERC20(_token).approve(address(connext), _amount);
+    IERC20(_token).approve(address(connext), 0);
+    IERC20(_token).approve(address(connext), _amount);
 
     IConnext(connext).xcall{value: (msg.value - _relayerFee)}(
       _destinationDomain, // _destination: Domain ID of the destination chain
```

**Comment by pauliax** [comment]
Escalate for 10 USDC.

First of all, it looks like some automated copy pasta submission. Second, opposite to other duplicates (#36), this issue failed to identify the exact problematic function. The given part of the codebase is not vulnerable because the approved amount is spent right after the approval in the same tx:
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L150-L157

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> First of all, it looks like some automated copy pasta submission. Second, opposite to other duplicates (#36), this issue failed to identify the exact problematic function. The given part of the codebase is not vulnerable because the approved amount is spent right after the approval in the same tx:
> https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L150-L157

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Not a valid issue as pointed out in the escalation

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Not a valid issue as pointed out in the escalation

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
