### ISSUE TITLE
cergyk - Double spend when relayerFee is zero in rebalanceXChain

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#23]
cergyk

high

# Double spend when relayerFee is zero in rebalanceXChain

## Summary
Any user can call `MainVault.rebalanceXChain` when the state of MainVault is `State.SendingFundsXChain`. 
However if a user calls this function with `relayerFee == 0` and `msg.value != 0`, msg.value is sent two times from the contract, resulting in a loss for the contract/protocol.

## Vulnerability Detail
The call is missing a check that `relayerFee != 0`, in which case in `XProvider.xTransferToController`:

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L332-L333

calling xTransfer:
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L152
msg.value is transferred once

calling pushFeedbackToXController -> xSend:
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XProvider.sol#L113-L115
relayerFee is set to be msg.value and msg.value is transferred the second time.

## Impact
Loss of funds for the protocol

## Tool used

Manual Review

## Recommendation
Check that `relayerFee != 0` when calling `rebalanceXChain`

**Comment by hrishibhat** [comment]
Based on the sponsor comment considering the issue as low since there would be no ether in the vault
