### ISSUE TITLE
evan - Pullfunds can end before the necessary funds have been pulled

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#250]
evan

medium

# Pullfunds can end before the necessary funds have been pulled

## Summary
Pullfunds can end before the necessary funds have been pulled. When this happens, the vault won't have enough balance to complete the subsequent steps.

## Vulnerability Detail
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L116-L122
Suppose shortage > balanceProtocol, and balanceProtocol < minimumPull, then this loop ends while there is still a shortage.

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L104
minimumPull is initialized to 1000000, and shortage will usually be greater than 1000000 (as long as the protocol has a low index). So if the protocol's balance is very low (maybe it was given a very low allocation), then this condition can be satisfied.

## Impact
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L310
When the vulnerability happens here, then there won't be enough fund for the subsequent transfer, causing rebalanceXChain to fail and the rebalance process to be interrupted. The vault will not be usable on all chains since deposit & withdraw functions require the vault to be in the idle state.

Also, as far as I can tell, there is no good way for the guardian to correct this. 

## Code Snippet

See Vulnerability Detail

## Tool used

Manual Review

## Recommendation
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L122
I believe it should be continue instead of break.

Duplicate of #273

**Comment by EvanYu0816** [comment]
Escalate for 10 USDC

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L116-L122
Please carefully examine this section of code again.

Pullfunds clearly breaks prematurely in the scenario I've described (shortage > balanceProtocol, and balanceProtocol < minimumPull which can happen when balanceProtocol is very low), so it doesn't pull the funds it needs to. Note that the shortage is not negligible:

Suppose pullFunds needs to pull some units of fund and most of that is in protocol 2. If the loop breaks prematurely in protocol 1, then there's a significant shortage. 

Again, as I mentioned, this interrupts the rebalance flow, and resuming isn't as simple as guardian calling a function - they actually have to send fund to the contract to make up for the shortage.

I believe this behavior in PullFunds is unintended. At the very least, the sponsor should be made aware of such possibility.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L116-L122
> Please carefully examine this section of code again.
> 
> Pullfunds clearly breaks prematurely in the scenario I've described (shortage > balanceProtocol, and balanceProtocol < minimumPull which can happen when balanceProtocol is very low), so it doesn't pull the funds it needs to. Note that the shortage is not negligible:
> 
> Suppose pullFunds needs to pull some units of fund and most of that is in protocol 2. If the loop breaks prematurely in protocol 1, then there's a significant shortage. 
> 
> Again, as I mentioned, this interrupts the rebalance flow, and resuming isn't as simple as guardian calling a function - they actually have to send fund to the contract to make up for the shortage.
> 
> I believe this behavior in PullFunds is unintended. At the very least, the sponsor should be made aware of such possibility.
> 
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

This issue is a duplicate of #273

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> This issue is a duplicate of #273 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
