### ISSUE TITLE
hyh - Beta pools performance isn't accounted for in player rewards

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#255]
hyh

high

# Beta pools performance isn't accounted for in player rewards

## Summary

Pool's performance is measured with the help of LP token price difference, which is Provider's exchangeRate() output.

BetaProvider's exchangeRate() is a noop, always returning zero.

## Vulnerability Detail

Performance of Beta pools will always be deemed zero and no rewards will be due for such allocations no matter how good realized profitability is.

## Impact

Rewards are lost for traders who allocated to Beta Finance, which is a violation of base protocol logic.

## Code Snippet

Vault's storePriceAndRewards() calculates strategy performance based on `currentPrice - lastPrices[_protocolId]`:

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L220-L245

```solidity
  /// @notice Stores the historical price and the reward per rounded locked token, ignoring decimals.
  /// @dev formula yield protocol i at time t: y(it) = (P(it) - P(it-1)) / P(it-1).
  /// @dev formula rewardPerLockedToken for protocol i at time t: r(it) = y(it) * TVL(t) * perfFee(t) / totalLockedTokens(t)
  /// @dev later, when the total rewards are calculated for a game player we multiply this (r(it)) by the locked tokens on protocol i at time t
  /// @param _totalUnderlying Totalunderlying = TotalUnderlyingInProtocols - BalanceVault.
  /// @param _protocolId Protocol id number.
  function storePriceAndRewards(uint256 _totalUnderlying, uint256 _protocolId) internal {
    uint256 currentPrice = price(_protocolId);
    if (lastPrices[_protocolId] == 0) {
      lastPrices[_protocolId] = currentPrice;
      return;
    }

    int256 priceDiff = int256(currentPrice - lastPrices[_protocolId]);
    int256 nominator = (int256(_totalUnderlying * performanceFee) * priceDiff);
    int256 totalAllocatedTokensRounded = totalAllocatedTokens / 1E18;
    int256 denominator = totalAllocatedTokensRounded * int256(lastPrices[_protocolId]) * 100; // * 100 cause perfFee is in percentages

    if (totalAllocatedTokensRounded == 0) {
      rewardPerLockedToken[rebalancingPeriod][_protocolId] = 0;
    } else {
      rewardPerLockedToken[rebalancingPeriod][_protocolId] = nominator / denominator;
    }

    lastPrices[_protocolId] = currentPrice;
  }
```

price() is Provider's exchangeRate():

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L381-L390

```solidity
  /// @notice Get price for underlying protocol
  /// @param _protocolNum Protocol number linked to an underlying protocol e.g compound_usdc_01
  /// @return protocolPrice Price per lp token
  function price(uint256 _protocolNum) public view returns (uint256) {
    IController.ProtocolInfoS memory protocol = controller.getProtocolInfo(
      vaultNumber,
      _protocolNum
    );
    return IProvider(protocol.provider).exchangeRate(protocol.LPToken);
  }
```

BetaProvider's exchangeRate() always return zero:

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Providers/BetaProvider.sol#L115-L120

```solidity
  /// @notice Not used for Beta
  /// @param _bToken Address of protocol LP Token eg yUSDC
  /// @return price of LP token
  function exchangeRate(address _bToken) public view override returns (uint256) {
    // return IBeta(_bToken).tokenPrice();
  }
```

## Tool used

Manual Review

## Recommendation

Consider returning LP token price in BetaProvider's exchangeRate().

Duplicate of #313

**Comment by dmitriia** [comment]
Escalate for 10 USDC
This is not a dup for 313, which is for Aave, this is for Beta.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> This is not a dup for 313, which is for Aave, this is for Beta.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected 

Issue #313 is valid for both cases. Given the nature of the issue, they can be put together as one.

**Comment by sherlock-admin** [comment]
> Escalation rejected 
> 
> Issue #313 is valid for both cases. Given the nature of the issue, they can be put together as one.

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
