### ISSUE TITLE
spyrosonic10 - Should not blacklist protocol when totalUnderlying is not withdrawn.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#280]
spyrosonic10

medium

# Should not blacklist protocol when totalUnderlying is not withdrawn.

## Summary
`blacklistProtocol()` method does not validate that all amount is withdrawn from the protocol

## Vulnerability Detail
Guardian can call `blacklistProtocol()` method of Vault.sol.  `balanceProtocol` is total balance in the protocol and this amount is withdrawn from protocol into the vault in `blacklistProtocol()` . It is not guaranteed that each protocol successfully withdraw requested amount. This method will mark protocol blacklisted no matter full amount is withdrawn or not. 

## Impact
If partial withdraw happen during call to `blacklistProtocol()` then fund will stuck in protocol unless `Dao` add same protocol again.  

## Code Snippet
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L477-L483

## Tool used

Manual Review

## Recommendation
Consider implementing something along these lines
- `blacklistProtocol` function can be used to 
  - call withdrawFromProtocol
  - and update allocation to zero
  - and check `if(balanceUnderlying() > 0)` then only update totalUnderlying as such and update state/flag to user later as needed.
  - and mark blacklisted
- A dedicated withdraw function to withdraw fund from protocol which is 
  - blacklisted 
  - and has 0 allocation 
  - and has non-zero LP tokens in Vault.

Duplicate of #156

**Comment by spyrosonic10** [comment]
Escalate for 10 USDC

This is not a duplicate of 217 and here is why.

- You will observe my reported issue whenever partial withdrawal from the provider happens. 217 does not have this relationship.
- My issue can be observed when the ecosystem has n number of providers on the other hand 217 only comes into picture when there is ONLY one provider is the ecosystem.
- Fix for 217 is simple but when it comes to this issue you will have to think about a proper fix as this involves partial withdrawal and the amount can still be left in protocol and in this case you do not want to mark protocol as blacklisted.

So I believe you can clearly see that the root cause, scenario and fixes all are different for both issues. So this is not a duplicate of 217.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This is not a duplicate of 217 and here is why.
> 
> - You will observe my reported issue whenever partial withdrawal from the provider happens. 217 does not have this relationship.
> - My issue can be observed when the ecosystem has n number of providers on the other hand 217 only comes into picture when there is ONLY one provider is the ecosystem.
> - Fix for 217 is simple but when it comes to this issue you will have to think about a proper fix as this involves partial withdrawal and the amount can still be left in protocol and in this case you do not want to mark protocol as blacklisted.
> 
> So I believe you can clearly see that the root cause, scenario and fixes all are different for both issues. So this is not a duplicate of 217. 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

#217 is not a valid duplicate of this issue. 
However this issue is a duplicate of #156

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> #217 is not a valid duplicate of this issue. 
> However this issue is a duplicate of #156 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
