### ISSUE TITLE
cergyk - Rounding error in storePriceAndRewards leads to loss of rewards

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#29]
cergyk

high

# Rounding error in storePriceAndRewards leads to loss of rewards

## Summary
In Vault.sol: when calling `storePriceAndRewards`, the difference of exchange rate for LP tokens to underlying is used to determine the rewards to accrue (for example the difference exchange rate from cUSDC to USDC).
However if the difference is small, and underlying tokens have low decimals (such as USDC with 6 decimals) the rounding error can round rewards to zero. 

## Vulnerability Detail
As seen in `storePriceAndRewards`:
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L226-L245

priceDiff:
`int256 priceDiff = int256(currentPrice - lastPrices[_protocolId]);`
can be a small 1e18 precision number (~1e16 is plausible)

_totalUnderlying is 1e6 precision number in the case of USDC

performanceFee is lower than 100

so 
`int256 nominator = (int256(_totalUnderlying * performanceFee) * priceDiff);`
is a 1e26 number

on the other hand `denominator`:
`int256 denominator = totalAllocatedTokensRounded * int256(lastPrices[_protocolId]) * 100;`

is a 1e38 number (totalAllocatedTokensRounded is 1e18).

It is very likely that the result of the division is rounded down to zero.

## Impact
Rewards are not distributed to protocol participants

## Tool used

Manual Review

## Recommendation
If rewards is zero, do not update `lastPrices[_protocolId]`

**Comment by eliteWalrus4164** [comment]
Escalate for 10 USDC

Agreed that the example scenario is flawed, as `totalAllocatedTokensRounded` is not of 1e18 precision because of division on the line:
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L235

However it pinpoints the root cause of the loss of precision, which is the fact that the price difference (`currentPrice - lastPrices[_protocolId]`) can be arbitrarily small, and thus denominator and nominator can be of similar precision, leading to loss of precision.
It should be considered a valid duplicate of #238, which is not 100% correct as well (see my escalation on it).

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Agreed that the example scenario is flawed, as `totalAllocatedTokensRounded` is not of 1e18 precision because of division on the line:
> https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L235
> 
> However it pinpoints the root cause of the loss of precision, which is the fact that the price difference (`currentPrice - lastPrices[_protocolId]`) can be arbitrarily small, and thus denominator and nominator can be of similar precision, leading to loss of precision.
> It should be considered a valid duplicate of #238, which is not 100% correct as well (see my escalation on it). 
> 
>  

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Considering this a valid duplicate of #238

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Considering this a valid duplicate of #238 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
