### ISSUE TITLE
HonorLt - Protocols dependence on each other

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#303]
HonorLt

high

# Protocols dependence on each other

## Summary

The system is depending that each of the protocols successfully performs the requested action.

## Vulnerability Detail

DAO can add a new protocol and attach it to the vault:
```solidity
  function addProtocol(
    string calldata _name,
    uint256 _vaultNumber,
    address _provider,
    address _protocolLPToken,
    address _underlying,
    address _govToken,
    uint256 _uScale
  ) external onlyDao returns (uint256) {
    uint256 protocolNumber = latestProtocolId[_vaultNumber];

    protocolNames[_vaultNumber][protocolNumber] = _name;
    protocolGovToken[_vaultNumber][protocolNumber] = _govToken;
    protocolInfo[_vaultNumber][protocolNumber] = ProtocolInfoS(
      _protocolLPToken,
      _provider,
      _underlying,
      _uScale
    );

    emit SetProtocolNumber(protocolNumber, _protocolLPToken);

    latestProtocolId[_vaultNumber]++;

    return protocolNumber;
  }
```

The system iterates over all the protocols in many cases, for example, when withdrawing funds:
```solidity
  function pullFunds(uint256 _value) internal {
    uint256 latestID = controller.latestProtocolId(vaultNumber);
    for (uint i = 0; i < latestID; i++) {
      ...
      withdrawFromProtocol(i, amountToWithdraw);
      ...
    }
  }
```

Because it iterates from the first to the last, it means that if any of the protocols fail to execute the action, all the remaining protocols will not get a chance to cover it. There are many more functions that perform similar iterations and actions.

An admin can try to blacklist the protocol, however,  it will not be possible if `withdrawFromProtocol` fails due to external reasons:
```solidity
  function blacklistProtocol(uint256 _protocolNum) external onlyGuardian {
    uint256 balanceProtocol = balanceUnderlying(_protocolNum);
    currentAllocations[_protocolNum] = 0;
    controller.setProtocolBlacklist(vaultNumber, _protocolNum);
    savedTotalUnderlying -= balanceProtocol;
    withdrawFromProtocol(_protocolNum, balanceProtocol);
  }
```

A specific example to illustrate the problem:
1) DAO adds 3 protocols: Aave, Beta, and Compound.
2) Users deposit funds.
3) A problem is discovered in Beta contracts and they pause their contracts.
4) Users try to withdraw, there are not enough funds on Aave, but the Compound is inaccessible because the Beta provider reverts.

All the other protocols cannot function if one of them reverts.

## Impact

The system relies upon all the protocols to succeed. If one of the protocols reverts, it will halt the execution of all the dependent functions. Once added there is no way to remove, edit, reorder, or pause the protocol leaving no possibility to recover.

## Code Snippet

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Controller.sol#L146-L171

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L111-L127

## Tool used

Manual Review

## Recommendation

Add remove/edit/pause functionality for individual protocols, or perform the action with a try/catch and act accordingly.

Duplicate of #128

**Comment by pauliax** [comment]
Escalate for 10 USDC.

Not explained why this was excluded. In my opinion, it is a valid concern.
Even the context file said that such issues are considerable:

_**Q: In case of external protocol integrations, are the risks of an external protocol pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.**
A: Partly ACCEPTABLE. So withdrawal from an underlying DeFi protocol back to the vault should be possible._

As mentioned in the issue, it will not be possible to withdraw from other protocols if one protocol is hacked or paused or whatever, and there is no possibility to remove it.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> Not explained why this was excluded. In my opinion, it is a valid concern.
> Even the context file said that such issues are considerable:
> 
> _**Q: In case of external protocol integrations, are the risks of an external protocol pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.**
> A: Partly ACCEPTABLE. So withdrawal from an underlying DeFi protocol back to the vault should be possible._
> 
> As mentioned in the issue, it will not be possible to withdraw from other protocols if one protocol is hacked or paused or whatever, and there is no possibility to remove it.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Considering this issue a valid duplicate of #128

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Considering this issue a valid duplicate of #128 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
