### ISSUE TITLE
Jeiwan - Vaults may become insolvent due to a missing conversion between protocol underlying tokens and vault underlying tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#314]
Jeiwan

high

# Vaults may become insolvent due to a missing conversion between protocol underlying tokens and vault underlying tokens

## Summary
The vaults support protocols with a different underlying token than the one used by a vault. This is accounted for when depositing and withdrawing to/from a protocol (tokens are swapped using Curve), however there's no conversion when computing total underlying balances. As a result, rebalancing of vaults may result a wrong distribution of tokens, not as set by the allocations. In the worst case scenario, the exchange rate of vault LP tokens can be wrong, leading to an insolvency of a vault.
## Vulnerability Detail
Derby vaults integrate with third-party protocols to generate yield on user-provided funds. A Derby vault is [configured to support only underlying token](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L98) (as per the documentation of the project, that's USDC), however there's possibility of integrating with protocols that use a different token (i.e. a different stablecoin, like USDT):
1. when funds are deposited to a protocol, they're [swapped for the protocol's underlying token](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L290-L297) if the token is different from the vault's token (e.g. protocol's token is USDT and vault's token is USDC);
1. likewise, funds are [swapped back when withdrawing from a protocol with a different underlying token](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L328-L335).

However, when calculating the total amount of underlying tokens deposited to protocols, there's no conversion between different tokens:
1. in the [pushTotalUnderlyingToController](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L249) function, `setTotalUnderlying` is called to calculate the amounts deposited to protocols;
1. [setTotalUnderlying](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L339) and [balanceUnderlying](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L352) don't convert token amounts using current market's price.

As a result, a vault can report a wrong balance to `XChainController` and, based on this wrong balance, `XChainController` will incorrectly distribute funds between networks. For example, if a protocol uses USDT, the exact amount of USDT will be reported to `XChainController` during rebalancing, but it should be converted to USDC using the market price.
## Impact
The entire accounting of the protocol can be impacted on different layers:
1. rebalancing will result in incorrect amounts assigned to vaults;
1. vaults will withdraw and deposit incorrect amount of funds during rebalancing;
1. gamer rewards may be miscalculated due to wrong underlying token balances.

In the worst case, the exchange rate of a vault, which is the [ratio of the sum of all funds deposited to protocols over the total supply of vault LP tokens](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XChainController.sol#L307), can cause an insolvency in a vault because there will be not enough underlying tokens to redeem all LP tokens for.
## Code Snippet
1. When a vault reports its deposited funds to `XChainController`, the total amount of deposited funds is computed:
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L252
1. A protocol may have a different underlying token, which is accounted for when depositing and withdrawing funds to/from the protocol:
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L282
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L307
1. The total amount of vault's deposited funds is computed as the sum of redeemable amounts in protocol vaults–there's no conversion between different underlying tokens (e.g. USDT and USDC):
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L339-L362
1. The exchange rate of vault LP tokens is the ratio of the total underlying amount of a vault over the total supply of LP tokens:
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/XChainController.sol#L307
## Tool used
Manual Review
## Recommendation
The best solution seems to be removing the support of different underlying tokens in third-party protocols. This will guarantee that the amount of underlying tokens of a vault won't reduce due to price fluctuations, which can cause different accounting problems to the Derby protocol.

Duplicate of #135

**Comment by Theezr** [comment]
Fix removed stable coin swap:
https://github.com/derbyfinance/derby-yield-optimiser/pull/196
