### ISSUE TITLE
bin2chen - pullFunds() break should not be used

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#351]
bin2chen

medium

# pullFunds() break should not be used

## Summary
Incorrectly jumped out of the loop, resulting in the amount less withdrawal from the protocol
## Vulnerability Detail
pullFunds() loops through all the protocols and tries to get enough `_value`
The code is as follows:
```solidity
  function pullFunds(uint256 _value) internal {
    uint256 latestID = controller.latestProtocolId(vaultNumber);
    for (uint i = 0; i < latestID; i++) {
      if (currentAllocations[i] == 0) continue;

      uint256 shortage = _value - vaultCurrency.balanceOf(address(this));
      uint256 balanceProtocol = balanceUnderlying(i);

      uint256 amountToWithdraw = shortage > balanceProtocol ? balanceProtocol : shortage;
      savedTotalUnderlying -= amountToWithdraw;

      if (amountToWithdraw < minimumPull) break; //<------break? may be have other protocol need to withdraw
      withdrawFromProtocol(i, amountToWithdraw);

      if (_value <= vaultCurrency.balanceOf(address(this))) break;
    }
  }
```
The above code shows that if `amountToWithdraw < minimumPull` then the whole loop is jumped out
but the `amountToWithdraw` maybe is the current protocol balance `balanceProtocol`
this skips the all next protocol, and there may still be enough amount to withdraw
It should just skip this protocol (continue)
All calls to pullFunds() will take less amount, such as rebalance(), rebalanceXChain()

## Impact

 rebalance(), rebalanceXChain() maybe take less funds

## Code Snippet
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L122
## Tool used

Manual Review

## Recommendation
```solidity
  function pullFunds(uint256 _value) internal {
    uint256 latestID = controller.latestProtocolId(vaultNumber);
    for (uint i = 0; i < latestID; i++) {
      if (currentAllocations[i] == 0) continue;

      uint256 shortage = _value - vaultCurrency.balanceOf(address(this));
      uint256 balanceProtocol = balanceUnderlying(i);

      uint256 amountToWithdraw = shortage > balanceProtocol ? balanceProtocol : shortage;
      savedTotalUnderlying -= amountToWithdraw;


-     if (amountToWithdraw < minimumPull) break;
+     if (amountToWithdraw < minimumPull) continue;
      withdrawFromProtocol(i, amountToWithdraw);

      if (_value <= vaultCurrency.balanceOf(address(this))) break;
    }
  }
```

Duplicate of #273

**Comment by bin2chen66** [comment]
Escalate for 10 USDC

This issue describes that "break" does not give the next Protocol a chance to withdraw. This should be the same as #273 . 

Please check it, thanks.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This issue describes that "break" does not give the next Protocol a chance to withdraw. This should be the same as #273 . 
> 
> Please check it, thanks.
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Duplicate of #273

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Duplicate of #273 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
