### ISSUE TITLE
hyh - Deposit and withdraw balance checks can be gamed by reentrancy in TruefiProvider, IdleProvider, YearnProvider, BetaProvider, CompoundProvider and AaveProvider

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#360]
hyh

high

# Deposit and withdraw balance checks can be gamed by reentrancy in TruefiProvider, IdleProvider, YearnProvider, BetaProvider, CompoundProvider and AaveProvider

## Summary

All Providers use balance difference to determine the amount to return to a user, and call external token contract inbetween.

As this token contract is user supplied, while all withdraw and deposit functions allow for reentrancy, the precooked contract can perform multiple nested deposits (or withdrawals) and record one transfer to Provider balance many times.

## Vulnerability Detail

Let's take CompoundProvider's withdraw() case (which isn't vulnerable to the another issue of fake token contract just reporting precooked numbers).

withdraw() records real `_uToken` balance (it has to be real in order for attacker to benefit) and calls user supplied `_cToken` contract, which can calls withdraw() in a nested way again and again before any transfers are done. This way intial balance recorded is the same in all nested calls. But for the first call the balance difference is the sum of all amounts of the transfers made.

Say Bob the attacker transferred 1 token in one direct and one nested call. Nested call will record 1 as balance difference, while first direct call will record `1 + 1 = 2` tokens, so Bob be credited with `2 + 1 = 3` tokens in total for both calls, while having spent only 2 tokens.

## Impact

Any IERC20 tokens can be stolen from Provider balances fully this way.

Even if all these contracts aren't supposed to hold balances, there are a spectre of cases when they end up possesing some meaningful funds (accumulated residuals, additional rewards supplied from the markets, user operational mistakes and so forth), which are attributed to protocol users, but can be stolen this way.

## Code Snippet

withdraw() can be reentered on external `_cToken` call, which allows for double+ counting of the real `_uToken` that were transferred to the Provider contract as a result of interactions with `_cToken`:

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Providers/CompoundProvider.sol#L56-L84

```solidity
  function withdraw(
    uint256 _amount,
    address _cToken,
    address _uToken
  ) external override returns (uint256) {
    uint256 balanceBefore = IERC20(_uToken).balanceOf(msg.sender);

    uint256 balanceBeforeRedeem = IERC20(_uToken).balanceOf(address(this));

    require(
      ICToken(_cToken).transferFrom(msg.sender, address(this), _amount) == true,
      "Error: transferFrom"
    );
    // Compound redeem: 0 on success, otherwise an Error code
    require(ICToken(_cToken).redeem(_amount) == 0, "Error: compound redeem");

    uint256 balanceAfterRedeem = IERC20(_uToken).balanceOf(address(this));
    uint256 uTokensReceived = balanceAfterRedeem - balanceBeforeRedeem;

    IERC20(_uToken).safeTransfer(msg.sender, uTokensReceived);

    uint256 balanceAfter = IERC20(_uToken).balanceOf(msg.sender);
    require(
      (balanceAfter - balanceBefore - uTokensReceived) == 0,
      "Error Withdraw: under/overflow"
    );

    return uTokensReceived;
  }
```

## Tool used

Manual Review

## Recommendation

Consider making all deposit and withdraw functions in all Providers `nonReentrant`.

Duplicate of #411

**Comment by hrishibhat** [comment]
Given that the providers can hold some funds through secondary rewards or other operations mistakes, loss of these funds is not considered a valid high/medium based on Sherlock rules. 
Considering this issue as low

**Comment by dmitriia** [comment]
Escalate for 10 USDC
The impact of the issue is any IERC20 tokens can be stolen from Provider balances fully. While Provider can never have the balance of underlying there might be balances of COMP as it is Provider address interacts with Compound and can be eligible for rewards.

It is assumed that `govToken` should end up being on the Vault balance:

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L404-L419

```solidity
  function claimTokens() public {
    uint256 latestID = controller.latestProtocolId(vaultNumber);
    for (uint i = 0; i < latestID; i++) {
      if (currentAllocations[i] == 0) continue;
>>    bool claim = controller.claim(vaultNumber, i);
      if (claim) {
        address govToken = controller.getGovToken(vaultNumber, i);
>>      uint256 tokenBalance = IERC20(govToken).balanceOf(address(this));
        Swap.swapTokensMulti(
          Swap.SwapInOut(tokenBalance, govToken, address(vaultCurrency)),
          controller.getUniswapParams(),
          false
        );
      }
    }
  }
```

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Controller.sol#L57-L70

```solidity
  function claim(
    uint256 _vaultNumber,
    uint256 _protocolNumber
  ) external override onlyVault returns (bool) {
    if (claimable[protocolInfo[_vaultNumber][_protocolNumber].LPToken]) {
      return
>>      IProvider(protocolInfo[_vaultNumber][_protocolNumber].provider).claim(
          protocolInfo[_vaultNumber][_protocolNumber].LPToken,
>>        msg.sender  // @audit it's Vault
        );
    } else {
      return false;
    }
  }
```

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Providers/CompoundProvider.sol#L131-L139

```solidity
  /// @notice Claims/harvest COMP tokens from the Comptroller
  /// @param _cToken Address of protocol LP Token eg cUSDC
  function claim(address _cToken, address _claimer) external override returns (bool) {
    address[] memory cTokens = new address[](1);
    cTokens[0] = _cToken;
>>  comptroller.claimComp(_claimer, cTokens);

    return true;
  }
```

But it is Provider address interacts with Compound, not Vault:

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Providers/CompoundProvider.sol#L27-L48

```solidity
  function deposit(
    uint256 _amount,
    address _cToken,
    address _uToken
  ) external override returns (uint256) {
    uint256 balanceBefore = IERC20(_uToken).balanceOf(address(this));

>>  IERC20(_uToken).safeTransferFrom(msg.sender, address(this), _amount);
    IERC20(_uToken).safeIncreaseAllowance(_cToken, _amount);

    uint256 balanceAfter = IERC20(_uToken).balanceOf(address(this));
    require((balanceAfter - balanceBefore - _amount) == 0, "Error Deposit: under/overflow");

    uint256 cTokenBefore = ICToken(_cToken).balanceOf(address(this));
>>  require(ICToken(_cToken).mint(_amount) == 0, "Error minting Compound");
    uint256 cTokenAfter = ICToken(_cToken).balanceOf(address(this));

    uint cTokensReceived = cTokenAfter - cTokenBefore;
    ICToken(_cToken).transfer(msg.sender, cTokensReceived);

    return cTokensReceived;
  }
```

So claiming for Vault can end up void, while claiming for CompoundProvider itself can be done by an attacker and all COMP rewards be immediately stolen as described in the issue.

This way the reward portion of the yield for the whole Vault can be stolen fully.

Reward yield can be quite substantial, say it is now 1/3 of the whole yield for mainnet DAI (1.4% DAI plus 0.7% COMP):

https://app.compound.finance/markets?market=v2

It looks like this is valid high severity.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> The impact of the issue is any IERC20 tokens can be stolen from Provider balances fully. While Provider can never have the balance of underlying there might be balances of COMP as it is Provider address interacts with Compound and can be eligible for rewards.
> 
> It is assumed that `govToken` should end up being on the Vault balance:
> 
> https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L404-L419
> 
> ```solidity
>   function claimTokens() public {
>     uint256 latestID = controller.latestProtocolId(vaultNumber);
>     for (uint i = 0; i < latestID; i++) {
>       if (currentAllocations[i] == 0) continue;
> >>    bool claim = controller.claim(vaultNumber, i);
>       if (claim) {
>         address govToken = controller.getGovToken(vaultNumber, i);
> >>      uint256 tokenBalance = IERC20(govToken).balanceOf(address(this));
>         Swap.swapTokensMulti(
>           Swap.SwapInOut(tokenBalance, govToken, address(vaultCurrency)),
>           controller.getUniswapParams(),
>           false
>         );
>       }
>     }
>   }
> ```
> 
> https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Controller.sol#L57-L70
> 
> ```solidity
>   function claim(
>     uint256 _vaultNumber,
>     uint256 _protocolNumber
>   ) external override onlyVault returns (bool) {
>     if (claimable[protocolInfo[_vaultNumber][_protocolNumber].LPToken]) {
>       return
> >>      IProvider(protocolInfo[_vaultNumber][_protocolNumber].provider).claim(
>           protocolInfo[_vaultNumber][_protocolNumber].LPToken,
> >>        msg.sender  // @audit it's Vault
>         );
>     } else {
>       return false;
>     }
>   }
> ```
> 
> https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Providers/CompoundProvider.sol#L131-L139
> 
> ```solidity
>   /// @notice Claims/harvest COMP tokens from the Comptroller
>   /// @param _cToken Address of protocol LP Token eg cUSDC
>   function claim(address _cToken, address _claimer) external override returns (bool) {
>     address[] memory cTokens = new address[](1);
>     cTokens[0] = _cToken;
> >>  comptroller.claimComp(_claimer, cTokens);
> 
>     return true;
>   }
> ```
> 
> But it is Provider address interacts with Compound, not Vault:
> 
> https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Providers/CompoundProvider.sol#L27-L48
> 
> ```solidity
>   function deposit(
>     uint256 _amount,
>     address _cToken,
>     address _uToken
>   ) external override returns (uint256) {
>     uint256 balanceBefore = IERC20(_uToken).balanceOf(address(this));
> 
> >>  IERC20(_uToken).safeTransferFrom(msg.sender, address(this), _amount);
>     IERC20(_uToken).safeIncreaseAllowance(_cToken, _amount);
> 
>     uint256 balanceAfter = IERC20(_uToken).balanceOf(address(this));
>     require((balanceAfter - balanceBefore - _amount) == 0, "Error Deposit: under/overflow");
> 
>     uint256 cTokenBefore = ICToken(_cToken).balanceOf(address(this));
> >>  require(ICToken(_cToken).mint(_amount) == 0, "Error minting Compound");
>     uint256 cTokenAfter = ICToken(_cToken).balanceOf(address(this));
> 
>     uint cTokensReceived = cTokenAfter - cTokenBefore;
>     ICToken(_cToken).transfer(msg.sender, cTokensReceived);
> 
>     return cTokensReceived;
>   }
> ```
> 
> So claiming for Vault can end up void, while claiming for CompoundProvider itself can be done by an attacker and all COMP rewards be immediately stolen as described in the issue.
> 
> This way the reward portion of the yield for the whole Vault can be stolen fully.
> 
> Reward yield can be quite substantial, say it is now 1/3 of the whole yield for mainnet DAI (1.4% DAI plus 0.7% COMP):
> 
> https://app.compound.finance/markets?market=v2
> 
> It looks like this is valid high severity.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Considering this issue Duplicate of #411

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Considering this issue Duplicate of #411 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
