### ISSUE TITLE
sayan_ - Unsafe type casting will cause miscalculation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#365]
sayan_

medium

# Unsafe type casting will cause miscalculation

## Summary
unsafe typecasting from `uint256` to `int256` will cause miscalculation
## Vulnerability Detail
same as summary
## Impact
miscalculation
## Code Snippet
[Vault.sol#L233-L234)](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L233-L234)
```solidity
File: contracts/Vault.sol
233:     int256 priceDiff = int256(currentPrice - lastPrices[_protocolId]);
234:     int256 nominator = (int256(_totalUnderlying * performanceFee) * priceDiff);
```

[Vault.sol#L236](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L236)
```solidity
File: contracts/Vault.sol
236:     int256 denominator = totalAllocatedTokensRounded * int256(lastPrices[_protocolId]) * 100; // * 100 cause perfFee is in percentages 

```
## Tool used

Manual Review

## Recommendation
use [OpenZeppelin's SafeCast](https://docs.openzeppelin.com/contracts/4.x/api/utils#SafeCast) when casting

**Comment by ghost** [comment]
Escalate for 10 USDC
This finding is wrongly classified as a duplicate of #334. While #334 describes an underflow exception being thrown due to wrong integer types (`uint256`) being used in subtraction before typecasting (to `int256`), this finding only speaks to the standard "unsafe" typecasting, which in this case is neither an actual problem nor would the recommendation fix the vulnerability in #334.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> This finding is wrongly classified as a duplicate of #334. While #334 describes an underflow exception being thrown due to wrong integer types (`uint256`) being used in subtraction before typecasting (to `int256`), this finding only speaks to the standard "unsafe" typecasting, which in this case is neither an actual problem nor would the recommendation fix the vulnerability in #334.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Not a valid duplicate of #334 and considering this issue as low/informational

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Not a valid duplicate of #334 and considering this issue as low/informational

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
