### ISSUE TITLE
chaduke - Nobody can deposit when getVaultBalance() < reservedFunds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#45]
chaduke

medium

# Nobody can deposit when getVaultBalance() < reservedFunds

## Summary
Nobody can deposit when ``getVaultBalance() < reservedFunds`` since the deposit() will revert under this case. 

## Vulnerability Detail
The ``deposit()`` function allows  a user to deposit vault currency and mint vault tokens. 

[https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L106-L124](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L106-L124)

However, the following lines that are used to measure the amount of vault currency sent by the user will revert when  ``getVaultBalance() < reservedFunds`` due to underflow, for example, when there are many withdrawl requests during a particular period. 

```javascript
 uint256 balanceBefore = getVaultBalance() - reservedFunds;
    vaultCurrency.safeTransferFrom(msg.sender, address(this), _amount);
    uint256 balanceAfter = getVaultBalance() - reservedFunds;
```
As a result, nobody can deposit any vault currency when ``getVaultBalance() < reservedFunds``. This is unfortunate, since deposits can mitigate the shortage of vault currencies. 

## Impact
Nobody can deposit when ``getVaultBalance() < reservedFunds`` since the deposit() will revert under this case. As a result, when many people withdraw at a particular period, nobody will be able to deposit and things can get worse like bank run.

## Code Snippet
See above

## Tool used
VSCode

Manual Review

## Recommendation
We only need to use `` getVaultBalance()`` to measure the amount of vault tokens sent by the user. 
```diff
function deposit(
    uint256 _amount,
    address _receiver
  ) external nonReentrant onlyWhenVaultIsOn returns (uint256 shares) {
    if (training) {
      require(whitelist[msg.sender]);
      uint256 balanceSender = (balanceOf(msg.sender) * exchangeRate) / (10 ** decimals());
      require(_amount + balanceSender <= maxTrainingDeposit);
    }

-    uint256 balanceBefore = getVaultBalance() - reservedFunds;
+    uint256 balanceBefore = getVaultBalance();
      vaultCurrency.safeTransferFrom(msg.sender, address(this), _amount);
-    uint256 balanceAfter = getVaultBalance() - reservedFunds;
+    uint256 balanceAfter = getVaultBalance();


    uint256 amount = balanceAfter - balanceBefore;
    shares = (amount * (10 ** decimals())) / exchangeRate;

    _mint(_receiver, shares);
  }

```
Duplicate of #262

**Comment by mister0y** [comment]
https://github.com/derbyfinance/derby-yield-optimiser/blob/master/contracts/MainVault.sol#L140
https://github.com/derbyfinance/derby-yield-optimiser/blob/master/contracts/MainVault.sol#L253
https://github.com/derbyfinance/derby-yield-optimiser/blob/master/contracts/Vault.sol#L161
