### ISSUE TITLE
rvierdiiev - User can block himself from future withdrawalRequest creating

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#57]
rvierdiiev

medium

# User can block himself from future withdrawalRequest creating

## Summary
User can block himself from future withdrawalRequest creating in case if he create request to withdraw 0 shares.
## Vulnerability Detail
`MainVault.withdrawalRequest` allows user to create request to withdraw funds after next rebalance.

https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L149-L162
```solidity
  function withdrawalRequest(
    uint256 _amount
  ) external nonReentrant onlyWhenVaultIsOn returns (uint256 value) {
    UserInfo storage user = userInfo[msg.sender];
    require(user.withdrawalRequestPeriod == 0, "Already a request");


    value = (_amount * exchangeRate) / (10 ** decimals());


    _burn(msg.sender, _amount);


    user.withdrawalAllowance = value;
    user.withdrawalRequestPeriod = rebalancingPeriod;
    totalWithdrawalRequests += value;
  }
```
As you can see if `user.withdrawalRequestPeriod != 0`, then he is not allowed to create new request. In other words, once you have not withdrawn request, you can't create new one.
Pls, note that you can create request for 0 amount of shares. Then `user.withdrawalAllowance` will be set to 0.

Once user does that, then he will not be able to call `withdrawAllowance` as it [doesn't allow `withdrawalAllowance` to be 0](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L168).
That means that function will [never delete `user.withdrawalRequestPeriod`](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L176), and user will not be able to create new request in future.
## Impact
Block of withdraw request functionality for user.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Do not allow to create request when `user.withdrawalAllowance` is 0.

**Comment by rvierdiiev** [comment]
Escalate for 10 usdc.
This is the problem for the sponsor, this was discussed with him. Looks like report was excluded and i ask to recheck with the sponsor. User can block himself forever.

**Comment by sherlock-admin** [comment]
> Escalate for 10 usdc.
> This is the problem for the sponsor, this was discussed with him. Looks like report was excluded and i ask to recheck with the sponsor. User can block himself forever.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

User sending withdrawal requests with zero amount and blocking themselves of future requests is not a valid high/medium

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> User sending withdrawal requests with zero amount and blocking themselves of future requests is not a valid high/medium

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
