### ISSUE TITLE
rvierdiiev - Game.redeemNegativeRewards doesn't take into account derby/vaultCurrency price when slashes derby tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#92]
rvierdiiev

high

# Game.redeemNegativeRewards doesn't take into account derby/vaultCurrency price when slashes derby tokens

## Summary
Game.redeemNegativeRewards doesn't take into account derby/vaultCurrency price when slashes derby tokens. Because rewards are set in vaultCurrency token, but amount is slashed in derby token, conversion should be added, that depends on derby/vaultCurrency price.
## Vulnerability Detail
Player of the `Game` earns rewards that are nominated in `vaultCurrency` token. Function `Vault.storePriceAndRewards` is responsible for fetching [exchange price of provider](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Vault.sol#L227) and then calculate rewards per locked derby token that depends on previous price and performance fee.

So when user wants to get rewards, he calls `Game.redeemRewards` which then [calls `redeemRewardsGame` function](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Game.sol#L552) and provides amount of tokens in `vaultCurrency` that user should receive. After that call user will be able to withdraw rewards through MainVault.

When user wants to withdraw rewards he calls `MainVault.withdrawRewards` function.
This function proves us that rewards are calculated in `vaultCurrency`. And in case if `swapRewards` is true, then they will be swapped for derby token, otherwise they will be sent as vaultCurrency token.
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/MainVault.sol#L220-L229
```solidity
    if (swapRewards) {
      uint256 tokensReceived = Swap.swapTokensMulti(
        Swap.SwapInOut(value, address(vaultCurrency), derbyToken),
        controller.getUniswapParams(),
        true
      );
      IERC20(derbyToken).safeTransfer(msg.sender, tokensReceived);
    } else {
      vaultCurrency.safeTransfer(msg.sender, value);
    }
```

So at this point we know that rewards for the players are accrued in the `vaultCurrency` token.

When player wants to unlock part of his derby tokens, that are locked in the game then he calls `Game.rebalanceBasket` with new allocations. Later `unlockTokensFromBasket` function will be called which [will slash](https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Game.sol#L280) some part of derby tokens is case if user has negative rewards balance.
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Game.sol#L296-L311
```solidity
  function redeemNegativeRewards(
    uint256 _basketId,
    uint256 _unlockedTokens
  ) internal returns (uint256) {
    int256 unredeemedRewards = baskets[_basketId].totalUnRedeemedRewards;
    if (unredeemedRewards > negativeRewardThreshold) return 0;


    uint256 tokensToBurn = (uint(-unredeemedRewards) * negativeRewardFactor) / 100;
    tokensToBurn = tokensToBurn < _unlockedTokens ? tokensToBurn : _unlockedTokens;


    baskets[_basketId].totalUnRedeemedRewards += int((tokensToBurn * 100) / negativeRewardFactor);


    IERC20(derbyToken).safeTransfer(homeVault, tokensToBurn);


    return tokensToBurn;
  }
```

The problem of this function is that it slashes derby tokens and uses `negativeRewardFactor` variable to calculate amount of derby tokens to slash.
This function should use derby/vaultCurrency price instead in order to calculate correct slash amount as price of derby token will not be same.

As result, because of that amount that is slashed will different every time when price changes.
For example when function will calculate that it's needed to slash 100 derby tokens, then 1 time this 100 tokens can cost 100$ and later they can cost 150$. But the price of negative rewards will be same.
As slashing depends on rewards which is nominated in `vaultCurrency` token, then derby slashing amount should depend on derby/vaultCurrency price.
## Impact
Different derby token amount is slashed for same rewards amount, when price of derby is changing relative to vaultCurrency token.
## Code Snippet
Provided above.
## Tool used

Manual Review

## Recommendation
Use price feed to calculate slashing amount.

**Comment by rvierdiiev** [comment]
Escalate for 10 usdc.
`negativeRewardFactor` can't be used as oracle price for the asses as it will be changing during the time(like all currencies). because of that you will not be able to adjust `negativeRewardFactor` every time(because you will need to do that multiple times per day), so price will be hardcoded and will not respect to real price. and in case of price changes, user will be slashed with bigger or less amount.
I believe that this is valid finding.

**Comment by sherlock-admin** [comment]
> Escalate for 10 usdc.
> `negativeRewardFactor` can't be used as oracle price for the asses as it will be changing during the time(like all currencies). because of that you will not be able to adjust `negativeRewardFactor` every time(because you will need to do that multiple times per day), so price will be hardcoded and will not respect to real price. and in case of price changes, user will be slashed with bigger or less amount.
> I believe that this is valid finding.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Based on Sponsor comment, this is acceptable as an early design limitation for an illiquid token, this issue can be considered low.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Based on Sponsor comment, this is acceptable as an early design limitation for an illiquid token, this issue can be considered low. 
> 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
