### ISSUE TITLE
Delvir0 - DerbyTokens that are sent by Game.sol to be burned are actually lost

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-01-derby-judging#97]
Delvir0

high

# DerbyTokens that are sent by Game.sol to be burned are actually lost

## Summary
Game.redeemNegativeRewards calculates tokens to burn and then sends them to MainVault.sol. 
MainVault doesn't have any functionalities to do anything with them thus they are stuck in the contract.
## Vulnerability Detail
See above
## Impact
Lost DerbyTokens
## Code Snippet
https://github.com/sherlock-audit/2023-01-derby/blob/main/derby-yield-optimiser/contracts/Game.sol#L296-L311
## Tool used

Manual Review

## Recommendation
Implement functionalities to process the tokens or send then to the DAO instead.

Duplicate of #124

**Comment by Delvir0** [comment]
Escalate for 10 USDC
Unknown why this got excluded. At Game.redeemNegativeRewards, comments indicate `@return tokensToBurn Amount of derby tokens that are burned`. 
These tokens are sent to `homeVault` which is `MainVault/ Vault`. Both do not have tokens to process or burn Derbytokens. 
Even if the intention was not to actually "burn" the tokens, they are stuck in a contract which is a vulnerability. 
I also confirmed this with a team member on Discord. If needed I can provide a screenshot.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> Unknown why this got excluded. At Game.redeemNegativeRewards, comments indicate `@return tokensToBurn Amount of derby tokens that are burned`. 
> These tokens are sent to `homeVault` which is `MainVault/ Vault`. Both do not have tokens to process or burn Derbytokens. 
> Even if the intention was not to actually "burn" the tokens, they are stuck in a contract which is a vulnerability. 
> I also confirmed this with a team member on Discord. If needed I can provide a screenshot. 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Considering this issue as a valid duplicate of #124 
However, since this has no impact on the totalUnderlying, considering it a low issue

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Considering this issue as a valid duplicate of #124 
> However, since this has no impact on the totalUnderlying, considering it a low issue

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
